services:
  db:
    image: postgres:17.0-bookworm
    restart: on-failure:3
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:
        - travel

networks:
  travel:
    driver: bridge
