[tool.poetry]
name = "travel-backend"
version = "0.1.0"
description = ""
authors = ["victor4pinheiro <victor.pinheiro.soft@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
