import clips

preference = """
(deftemplate preferencia
    (slot ponto (type SYMBOL))
    (slot hospedagem (type SYMBOL))
    (slot clima (type SYMBOL))
    (slot alimentacao (type SYMBOL)))
"""
city = """
(deftemplate recommendation
    (slot cidade))
"""

environment = clips.Environment()
environment.build(preference)
environment.build(city)

r1 = '(defrule r1 (preferencia (ponto natureza) (hospedagem hotel) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r1)
r2 = '(defrule r2 (preferencia (ponto natureza) (hospedagem hotel) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r2)
r3 = '(defrule r3 (preferencia (ponto natureza) (hospedagem hotel) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r3)
r4 = '(defrule r4 (preferencia (ponto natureza) (hospedagem hotel) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r4)
r5 = '(defrule r5 (preferencia (ponto natureza) (hospedagem hotel) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r5)
r6 = '(defrule r6 (preferencia (ponto natureza) (hospedagem hotel) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r6)
r7 = '(defrule r7 (preferencia (ponto natureza) (hospedagem hotel) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r7)
r8 = '(defrule r8 (preferencia (ponto natureza) (hospedagem hotel) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r8)
r9 = '(defrule r9 (preferencia (ponto natureza) (hospedagem hotel) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r9)
r10 = '(defrule r10 (preferencia (ponto natureza) (hospedagem hotel) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r10)
r11 = '(defrule r11 (preferencia (ponto natureza) (hospedagem hotel) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r11)
r12 = '(defrule r12 (preferencia (ponto natureza) (hospedagem hotel) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r12)
r13 = '(defrule r13 (preferencia (ponto natureza) (hospedagem hotel) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r13)
r14 = '(defrule r14 (preferencia (ponto natureza) (hospedagem hotel) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r14)
r15 = '(defrule r15 (preferencia (ponto natureza) (hospedagem hotel) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r15)
r16 = '(defrule r16 (preferencia (ponto natureza) (hospedagem airbnb) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r16)
r17 = '(defrule r17 (preferencia (ponto natureza) (hospedagem airbnb) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r17)
r18 = '(defrule r18 (preferencia (ponto natureza) (hospedagem airbnb) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r18)
r19 = '(defrule r19 (preferencia (ponto natureza) (hospedagem airbnb) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r19)
r20 = '(defrule r20 (preferencia (ponto natureza) (hospedagem airbnb) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r20)
r21 = '(defrule r21 (preferencia (ponto natureza) (hospedagem airbnb) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r21)
r22 = '(defrule r22 (preferencia (ponto natureza) (hospedagem airbnb) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r22)
r23 = '(defrule r23 (preferencia (ponto natureza) (hospedagem airbnb) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r23)
r24 = '(defrule r24 (preferencia (ponto natureza) (hospedagem airbnb) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r24)
r25 = '(defrule r25 (preferencia (ponto natureza) (hospedagem airbnb) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r25)
r26 = '(defrule r26 (preferencia (ponto natureza) (hospedagem airbnb) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r26)
r27 = '(defrule r27 (preferencia (ponto natureza) (hospedagem airbnb) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r27)
r28 = '(defrule r28 (preferencia (ponto natureza) (hospedagem airbnb) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r28)
r29 = '(defrule r29 (preferencia (ponto natureza) (hospedagem airbnb) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r29)
r30 = '(defrule r30 (preferencia (ponto natureza) (hospedagem airbnb) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r30)
r31 = '(defrule r31 (preferencia (ponto natureza) (hospedagem hostel) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r31)
r32 = '(defrule r32 (preferencia (ponto natureza) (hospedagem hostel) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r32)
r33 = '(defrule r33 (preferencia (ponto natureza) (hospedagem hostel) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r33)
r34 = '(defrule r34 (preferencia (ponto natureza) (hospedagem hostel) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r34)
r35 = '(defrule r35 (preferencia (ponto natureza) (hospedagem hostel) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r35)
r36 = '(defrule r36 (preferencia (ponto natureza) (hospedagem hostel) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r36)
r37 = '(defrule r37 (preferencia (ponto natureza) (hospedagem hostel) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r37)
r38 = '(defrule r38 (preferencia (ponto natureza) (hospedagem hostel) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r38)
r39 = '(defrule r39 (preferencia (ponto natureza) (hospedagem hostel) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r39)
r40 = '(defrule r40 (preferencia (ponto natureza) (hospedagem hostel) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r40)
r41 = '(defrule r41 (preferencia (ponto natureza) (hospedagem hostel) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r41)
r42 = '(defrule r42 (preferencia (ponto natureza) (hospedagem hostel) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r42)
r43 = '(defrule r43 (preferencia (ponto natureza) (hospedagem hostel) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r43)
r44 = '(defrule r44 (preferencia (ponto natureza) (hospedagem hostel) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r44)
r45 = '(defrule r45 (preferencia (ponto natureza) (hospedagem hostel) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r45)
r46 = '(defrule r46 (preferencia (ponto natureza) (hospedagem acampamento) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r46)
r47 = '(defrule r47 (preferencia (ponto natureza) (hospedagem acampamento) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r47)
r48 = '(defrule r48 (preferencia (ponto natureza) (hospedagem acampamento) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r48)
r49 = '(defrule r49 (preferencia (ponto natureza) (hospedagem acampamento) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r49)
r50 = '(defrule r50 (preferencia (ponto natureza) (hospedagem acampamento) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r50)
r51 = '(defrule r51 (preferencia (ponto natureza) (hospedagem acampamento) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r51)
r52 = '(defrule r52 (preferencia (ponto natureza) (hospedagem acampamento) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r52)
r53 = '(defrule r53 (preferencia (ponto natureza) (hospedagem acampamento) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r53)
r54 = '(defrule r54 (preferencia (ponto natureza) (hospedagem acampamento) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r54)
r55 = '(defrule r55 (preferencia (ponto natureza) (hospedagem acampamento) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r55)
r56 = '(defrule r56 (preferencia (ponto natureza) (hospedagem acampamento) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r56)
r57 = '(defrule r57 (preferencia (ponto natureza) (hospedagem acampamento) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r57)
r58 = '(defrule r58 (preferencia (ponto natureza) (hospedagem acampamento) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r58)
r59 = '(defrule r59 (preferencia (ponto natureza) (hospedagem acampamento) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r59)
r60 = '(defrule r60 (preferencia (ponto natureza) (hospedagem acampamento) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r60)
r61 = '(defrule r61 (preferencia (ponto cultura) (hospedagem hotel) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r61)
r62 = '(defrule r62 (preferencia (ponto cultura) (hospedagem hotel) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r62)
r63 = '(defrule r63 (preferencia (ponto cultura) (hospedagem hotel) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r63)
r64 = '(defrule r64 (preferencia (ponto cultura) (hospedagem hotel) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r64)
r65 = '(defrule r65 (preferencia (ponto cultura) (hospedagem hotel) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r65)
r66 = '(defrule r66 (preferencia (ponto cultura) (hospedagem hotel) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r66)
r67 = '(defrule r67 (preferencia (ponto cultura) (hospedagem hotel) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r67)
r68 = '(defrule r68 (preferencia (ponto cultura) (hospedagem hotel) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r68)
r69 = '(defrule r69 (preferencia (ponto cultura) (hospedagem hotel) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r69)
r70 = '(defrule r70 (preferencia (ponto cultura) (hospedagem hotel) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r70)
r71 = '(defrule r71 (preferencia (ponto cultura) (hospedagem hotel) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r71)
r72 = '(defrule r72 (preferencia (ponto cultura) (hospedagem hotel) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r72)
r73 = '(defrule r73 (preferencia (ponto cultura) (hospedagem hotel) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r73)
r74 = '(defrule r74 (preferencia (ponto cultura) (hospedagem hotel) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r74)
r75 = '(defrule r75 (preferencia (ponto cultura) (hospedagem hotel) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r75)
r76 = '(defrule r76 (preferencia (ponto cultura) (hospedagem airbnb) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r76)
r77 = '(defrule r77 (preferencia (ponto cultura) (hospedagem airbnb) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r77)
r78 = '(defrule r78 (preferencia (ponto cultura) (hospedagem airbnb) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r78)
r79 = '(defrule r79 (preferencia (ponto cultura) (hospedagem airbnb) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r79)
r80 = '(defrule r80 (preferencia (ponto cultura) (hospedagem airbnb) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r80)
r81 = '(defrule r81 (preferencia (ponto cultura) (hospedagem airbnb) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r81)
r82 = '(defrule r82 (preferencia (ponto cultura) (hospedagem airbnb) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r82)
r83 = '(defrule r83 (preferencia (ponto cultura) (hospedagem airbnb) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r83)
r84 = '(defrule r84 (preferencia (ponto cultura) (hospedagem airbnb) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r84)
r85 = '(defrule r85 (preferencia (ponto cultura) (hospedagem airbnb) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r85)
r86 = '(defrule r86 (preferencia (ponto cultura) (hospedagem airbnb) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r86)
r87 = '(defrule r87 (preferencia (ponto cultura) (hospedagem airbnb) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r87)
r88 = '(defrule r88 (preferencia (ponto cultura) (hospedagem airbnb) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r88)
r89 = '(defrule r89 (preferencia (ponto cultura) (hospedagem airbnb) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r89)
r90 = '(defrule r90 (preferencia (ponto cultura) (hospedagem airbnb) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r90)
r91 = '(defrule r91 (preferencia (ponto cultura) (hospedagem hostel) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r91)
r92 = '(defrule r92 (preferencia (ponto cultura) (hospedagem hostel) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r92)
r93 = '(defrule r93 (preferencia (ponto cultura) (hospedagem hostel) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r93)
r94 = '(defrule r94 (preferencia (ponto cultura) (hospedagem hostel) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r94)
r95 = '(defrule r95 (preferencia (ponto cultura) (hospedagem hostel) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r95)
r96 = '(defrule r96 (preferencia (ponto cultura) (hospedagem hostel) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r96)
r97 = '(defrule r97 (preferencia (ponto cultura) (hospedagem hostel) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r97)
r98 = '(defrule r98 (preferencia (ponto cultura) (hospedagem hostel) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r98)
r99 = '(defrule r99 (preferencia (ponto cultura) (hospedagem hostel) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r99)
r100 = '(defrule r100 (preferencia (ponto cultura) (hospedagem hostel) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r100)
r101 = '(defrule r101 (preferencia (ponto cultura) (hospedagem hostel) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r101)
r102 = '(defrule r102 (preferencia (ponto cultura) (hospedagem hostel) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r102)
r103 = '(defrule r103 (preferencia (ponto cultura) (hospedagem hostel) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r103)
r104 = '(defrule r104 (preferencia (ponto cultura) (hospedagem hostel) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r104)
r105 = '(defrule r105 (preferencia (ponto cultura) (hospedagem hostel) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r105)
r106 = '(defrule r106 (preferencia (ponto cultura) (hospedagem acampamento) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r106)
r107 = '(defrule r107 (preferencia (ponto cultura) (hospedagem acampamento) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r107)
r108 = '(defrule r108 (preferencia (ponto cultura) (hospedagem acampamento) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r108)
r109 = '(defrule r109 (preferencia (ponto cultura) (hospedagem acampamento) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r109)
r110 = '(defrule r110 (preferencia (ponto cultura) (hospedagem acampamento) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r110)
r111 = '(defrule r111 (preferencia (ponto cultura) (hospedagem acampamento) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r111)
r112 = '(defrule r112 (preferencia (ponto cultura) (hospedagem acampamento) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r112)
r113 = '(defrule r113 (preferencia (ponto cultura) (hospedagem acampamento) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r113)
r114 = '(defrule r114 (preferencia (ponto cultura) (hospedagem acampamento) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r114)
r115 = '(defrule r115 (preferencia (ponto cultura) (hospedagem acampamento) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r115)
r116 = '(defrule r116 (preferencia (ponto cultura) (hospedagem acampamento) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r116)
r117 = '(defrule r117 (preferencia (ponto cultura) (hospedagem acampamento) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r117)
r118 = '(defrule r118 (preferencia (ponto cultura) (hospedagem acampamento) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r118)
r119 = '(defrule r119 (preferencia (ponto cultura) (hospedagem acampamento) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r119)
r120 = '(defrule r120 (preferencia (ponto cultura) (hospedagem acampamento) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r120)
r121 = '(defrule r121 (preferencia (ponto aventura) (hospedagem hotel) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r121)
r122 = '(defrule r122 (preferencia (ponto aventura) (hospedagem hotel) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r122)
r123 = '(defrule r123 (preferencia (ponto aventura) (hospedagem hotel) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r123)
r124 = '(defrule r124 (preferencia (ponto aventura) (hospedagem hotel) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r124)
r125 = '(defrule r125 (preferencia (ponto aventura) (hospedagem hotel) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r125)
r126 = '(defrule r126 (preferencia (ponto aventura) (hospedagem hotel) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r126)
r127 = '(defrule r127 (preferencia (ponto aventura) (hospedagem hotel) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r127)
r128 = '(defrule r128 (preferencia (ponto aventura) (hospedagem hotel) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r128)
r129 = '(defrule r129 (preferencia (ponto aventura) (hospedagem hotel) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r129)
r130 = '(defrule r130 (preferencia (ponto aventura) (hospedagem hotel) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r130)
r131 = '(defrule r131 (preferencia (ponto aventura) (hospedagem hotel) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r131)
r132 = '(defrule r132 (preferencia (ponto aventura) (hospedagem hotel) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r132)
r133 = '(defrule r133 (preferencia (ponto aventura) (hospedagem hotel) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r133)
r134 = '(defrule r134 (preferencia (ponto aventura) (hospedagem hotel) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r134)
r135 = '(defrule r135 (preferencia (ponto aventura) (hospedagem hotel) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r135)
r136 = '(defrule r136 (preferencia (ponto aventura) (hospedagem airbnb) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r136)
r137 = '(defrule r137 (preferencia (ponto aventura) (hospedagem airbnb) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r137)
r138 = '(defrule r138 (preferencia (ponto aventura) (hospedagem airbnb) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r138)
r139 = '(defrule r139 (preferencia (ponto aventura) (hospedagem airbnb) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r139)
r140 = '(defrule r140 (preferencia (ponto aventura) (hospedagem airbnb) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r140)
r141 = '(defrule r141 (preferencia (ponto aventura) (hospedagem airbnb) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r141)
r142 = '(defrule r142 (preferencia (ponto aventura) (hospedagem airbnb) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r142)
r143 = '(defrule r143 (preferencia (ponto aventura) (hospedagem airbnb) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r143)
r144 = '(defrule r144 (preferencia (ponto aventura) (hospedagem airbnb) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r144)
r145 = '(defrule r145 (preferencia (ponto aventura) (hospedagem airbnb) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r145)
r146 = '(defrule r146 (preferencia (ponto aventura) (hospedagem airbnb) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r146)
r147 = '(defrule r147 (preferencia (ponto aventura) (hospedagem airbnb) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r147)
r148 = '(defrule r148 (preferencia (ponto aventura) (hospedagem airbnb) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r148)
r149 = '(defrule r149 (preferencia (ponto aventura) (hospedagem airbnb) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r149)
r150 = '(defrule r150 (preferencia (ponto aventura) (hospedagem airbnb) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r150)
r151 = '(defrule r151 (preferencia (ponto aventura) (hospedagem hostel) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r151)
r152 = '(defrule r152 (preferencia (ponto aventura) (hospedagem hostel) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r152)
r153 = '(defrule r153 (preferencia (ponto aventura) (hospedagem hostel) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r153)
r154 = '(defrule r154 (preferencia (ponto aventura) (hospedagem hostel) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r154)
r155 = '(defrule r155 (preferencia (ponto aventura) (hospedagem hostel) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r155)
r156 = '(defrule r156 (preferencia (ponto aventura) (hospedagem hostel) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r156)
r157 = '(defrule r157 (preferencia (ponto aventura) (hospedagem hostel) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r157)
r158 = '(defrule r158 (preferencia (ponto aventura) (hospedagem hostel) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r158)
r159 = '(defrule r159 (preferencia (ponto aventura) (hospedagem hostel) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r159)
r160 = '(defrule r160 (preferencia (ponto aventura) (hospedagem hostel) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r160)
r161 = '(defrule r161 (preferencia (ponto aventura) (hospedagem hostel) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r161)
r162 = '(defrule r162 (preferencia (ponto aventura) (hospedagem hostel) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r162)
r163 = '(defrule r163 (preferencia (ponto aventura) (hospedagem hostel) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r163)
r164 = '(defrule r164 (preferencia (ponto aventura) (hospedagem hostel) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r164)
r165 = '(defrule r165 (preferencia (ponto aventura) (hospedagem hostel) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r165)
r166 = '(defrule r166 (preferencia (ponto aventura) (hospedagem acampamento) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r166)
r167 = '(defrule r167 (preferencia (ponto aventura) (hospedagem acampamento) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r167)
r168 = '(defrule r168 (preferencia (ponto aventura) (hospedagem acampamento) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r168)
r169 = '(defrule r169 (preferencia (ponto aventura) (hospedagem acampamento) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r169)
r170 = '(defrule r170 (preferencia (ponto aventura) (hospedagem acampamento) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r170)
r171 = '(defrule r171 (preferencia (ponto aventura) (hospedagem acampamento) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r171)
r172 = '(defrule r172 (preferencia (ponto aventura) (hospedagem acampamento) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r172)
r173 = '(defrule r173 (preferencia (ponto aventura) (hospedagem acampamento) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r173)
r174 = '(defrule r174 (preferencia (ponto aventura) (hospedagem acampamento) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r174)
r175 = '(defrule r175 (preferencia (ponto aventura) (hospedagem acampamento) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r175)
r176 = '(defrule r176 (preferencia (ponto aventura) (hospedagem acampamento) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r176)
r177 = '(defrule r177 (preferencia (ponto aventura) (hospedagem acampamento) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r177)
r178 = '(defrule r178 (preferencia (ponto aventura) (hospedagem acampamento) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r178)
r179 = '(defrule r179 (preferencia (ponto aventura) (hospedagem acampamento) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r179)
r180 = '(defrule r180 (preferencia (ponto aventura) (hospedagem acampamento) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r180)
r181 = '(defrule r181 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r181)
r182 = '(defrule r182 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r182)
r183 = '(defrule r183 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r183)
r184 = '(defrule r184 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r184)
r185 = '(defrule r185 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r185)
r186 = '(defrule r186 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r186)
r187 = '(defrule r187 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r187)
r188 = '(defrule r188 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r188)
r189 = '(defrule r189 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r189)
r190 = '(defrule r190 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r190)
r191 = '(defrule r191 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r191)
r192 = '(defrule r192 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r192)
r193 = '(defrule r193 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r193)
r194 = '(defrule r194 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r194)
r195 = '(defrule r195 (preferencia (ponto vida_noturna) (hospedagem hotel) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r195)
r196 = '(defrule r196 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r196)
r197 = '(defrule r197 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r197)
r198 = '(defrule r198 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r198)
r199 = '(defrule r199 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r199)
r200 = '(defrule r200 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r200)
r201 = '(defrule r201 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r201)
r202 = '(defrule r202 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r202)
r203 = '(defrule r203 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r203)
r204 = '(defrule r204 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r204)
r205 = '(defrule r205 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r205)
r206 = '(defrule r206 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r206)
r207 = '(defrule r207 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r207)
r208 = '(defrule r208 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r208)
r209 = '(defrule r209 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r209)
r210 = '(defrule r210 (preferencia (ponto vida_noturna) (hospedagem airbnb) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r210)
r211 = '(defrule r211 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r211)
r212 = '(defrule r212 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r212)
r213 = '(defrule r213 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r213)
r214 = '(defrule r214 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r214)
r215 = '(defrule r215 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r215)
r216 = '(defrule r216 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r216)
r217 = '(defrule r217 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r217)
r218 = '(defrule r218 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r218)
r219 = '(defrule r219 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r219)
r220 = '(defrule r220 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r220)
r221 = '(defrule r221 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r221)
r222 = '(defrule r222 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r222)
r223 = '(defrule r223 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r223)
r224 = '(defrule r224 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r224)
r225 = '(defrule r225 (preferencia (ponto vida_noturna) (hospedagem hostel) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r225)
r226 = '(defrule r226 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima equatorial) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r226)
r227 = '(defrule r227 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima equatorial) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r227)
r228 = '(defrule r228 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima equatorial) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r228)
r229 = '(defrule r229 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima equatorial) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r229)
r230 = '(defrule r230 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima equatorial) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r230)
r231 = '(defrule r231 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima tropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r231)
r232 = '(defrule r232 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima tropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r232)
r233 = '(defrule r233 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima tropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r233)
r234 = '(defrule r234 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima tropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r234)
r235 = '(defrule r235 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima tropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r235)
r236 = '(defrule r236 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima subtropical) (alimentacao massa)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r236)
r237 = '(defrule r237 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima subtropical) (alimentacao hamburger)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r237)
r238 = '(defrule r238 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima subtropical) (alimentacao sushi)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r238)
r239 = '(defrule r239 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima subtropical) (alimentacao churrasco)) => (assert (recommendation (cidade "Salvador"))))'; environment.build(r239)
r240 = '(defrule r240 (preferencia (ponto vida_noturna) (hospedagem acampamento) (clima subtropical) (alimentacao sobremesas)) => (assert (recommendation (cidade "sao paulo"))))'; environment.build(r240)


def recommend_data(ponto, hospedagem, clima, alimentacao):
    template = environment.find_template('preferencia')
    fact = template.assert_fact(ponto=clips.Symbol(ponto),hospedagem=clips.Symbol(hospedagem),clima=clips.Symbol(clima),alimentacao=clips.Symbol(alimentacao))
    environment.run()
    recommendation_facts = [fact for fact in environment.facts() if fact.template.name == "recommendation"]
    for recommendation in recommendation_facts:
        return recommendation["cidade"]

#recommend_data('vida_noturna','hotel','tropical','churrasco')
#print(recommend_data('vida_noturna','acampamento','subtropical','sobremesas'))
